name: "VL"

### Keyword arguments to the ffa_search() function ###
search:
    period_min: 5.00
    period_max: 60.00
    bins_min: 960
    bins_max: 1040
    fpmin: 10
    rmed_width: 8.0
    rmed_minpts: 101
    wtsp: 1.5
    threads: 1

### Keyword arguments to the find_peaks() function ###
detect:
    # Length of a periodogram segment in number of DFT bins.
    segment_dftbins_length: 30.0

    # Minimum number of segments a periodogram must contain for the dynamic
    # selection threshold to be applied. If the number of segments is lower,
    # a constant 'snr_min' threshold is applied.
    min_segments: 8

    # Minimum S/N for a peak in a periodogram to be reported, even if it
    # exceeds the dynamic selection threshold.
    snr_min: 9.0

    # Controls the dynamic S/N selection threshold. Periodograms are split in
    # segments, and for each segment the median and robust standard deviations
    # are calculated. At the center of this segment, the selection threshold is
    # taken to be median + nsigma x robust_std. A polynomial in log(period)
    # is then fitted to the set of reference points thus obtained (see below).
    nsigma: 9.0

    # Degree of polynomial in log(period) fitted to the selection threshold
    # reference points.
    polydeg: 2

    # Peak clustering radius expressed in number of DFT bins.
    peak_clustering_radius: 0.20

    # For every detection flagged in a periodogram, we extract a slice of the
    # periodogram centered on the peak's period. The width of this slice
    # expressed in number of DFT bins is the number below.
    period_slice_width: 2.0

### Candidate parameters ###
candidates:
    # Number of phase bins used to produce the final folded sub-integrations.
    # The code will always limit nbins to int(period / sampling_time).
    nbins: 1024

    # Number of sub-integrations requested. The code will always limit nsubs to
    # int(tobs / period).
    nsubs: 128
